# ~/.zprofile is sourced by zsh on login

# Source standard POSIX profile for system-wide PATHs (like JetBrains Toolbox)
[[ -f ~/.profile ]] && emulate sh -c 'source ~/.profile'

# pnpm path
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
